repos:
  # --- Formateo automático ---
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3

  # --- Ordenar imports automáticamente ---
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.12.0
    hooks:
      - id: isort
        name: isort (import sorter)
        args: ["--profile", "black"]

  # --- Análisis estático / estilo de código ---
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-simplify==0.21.0]
        args: [
          "--max-line-length=88",
          "--extend-ignore=E203",
          "--statistics"
        ]
